server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  profiles:
    active: dev
    servlet:
      multipart:
        max-file-size: 50MB
jwt:
  signerKey: "UWOG67IDTlxApTrrn3ukTybaTHxvUyCuQ2FjMcTeRclpqNiPe9Yr3Fyt1j8zlvjn"
