spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/koi-care-system
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: storephuoc@gmail.com
      password: ncux oxqc ldqu leih
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000       #application doesn't wait if the SMTP server takes too long to respond.
